name: Run Postman Collection

on:
  push:
    branches:
      - ci-api-testing
  workflow_dispatch:

jobs:
  run-postman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start containers 🐳
        run: |
          export DISABLE_LOGGING=true
          docker compose -f docker-compose.yml up -d
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
      - name: Create & Seed database 🌱
        run: |
          docker compose exec -T laravel-api php artisan migrate:refresh --seed
      - name: GET Version
        run: curl -v -X GET 'http://localhost:8091/status'

      - name: Install Newman
        run: npm install -g newman

      - name: Download Postman Collection from API
        run: |
          curl --location \
          --request GET "https://api.getpostman.com/collections/${{ secrets.POSTMAN_COLLECTION_ID }}" \
          --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
          --output collection.json

      - name: Run Postman Collection with Newman
        run: newman run collection.json --iteration-data "./test-data.csv"
